SELECT STORE.ID AS STORE_ID,
  EVENTS.ID     AS EVENT_ID,
  EVENTS.NAME,
  EVENTS.EVENT_TYPE_ID,
  EVENTS.DESCR,
  TO_CHAR(EVENTS.START_DATE,'yyyy-MM-dd') AS START_DATE,
  TO_CHAR(EVENTS.END_DATE,'yyyy-MM-dd') AS END_DATE,
  EVENTS.DESCR2
FROM NM_STORE_EVENTS EVENTS,
  NM_LOCATION_EVENT MV,
  NM_STORE_LOCATION STORE
WHERE EVENTS.ID     =MV.EVENT_ID
AND MV.STORE_ID     =STORE.ID
AND STORE.STORE_TYPE='standard'
ORDER BY STORE.ID,
  EVENTS.ID
  