FROM frolvlad/alpine-oraclejdk8:slim

ENV DYNAMODB_VERSION=latest

ENV AWS_ACCESS_KEY_ID DummyAccessKeyId
ENV AWS_SECRET_ACCESS_KEY DummySecretAccessKey
ENV AWS_DEFAULT_REGION us-west-2

RUN apk add --no-cache curl 

RUN curl -O https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_${DYNAMODB_VERSION}.tar.gz && \
    tar zxvf dynamodb_local_${DYNAMODB_VERSION}.tar.gz && \
    rm dynamodb_local_${DYNAMODB_VERSION}.tar.gz

EXPOSE 8000

ENTRYPOINT ["java", "-Djava.library.path=.", "-jar", "DynamoDBLocal.jar",  "--sharedDb", "-inMemory"]