FROM frolvlad/alpine-oraclejdk8:slim
ENV ENV_NAME docker

ENV AWS_ACCESS_KEY_ID DummyAccessKeyId
ENV AWS_SECRET_ACCESS_KEY DummySecretAccessKey
ENV AWS_DEFAULT_REGION us-west-2

RUN apk add --update python3 && \
    python3 -m ensurepip --upgrade && \
    pip3 install awscli && \
    rm -rf /var/cache/apk/*
