package com.sixthday.bootstrap.info.logging;

public class LoggingAction {
    public static final String GET_CATEGORIES_FROM_CATEGORY_SERVICE = "GET_CATEGORIES_FROM_CATEGORY_SERVICE";
    public static final String GET_CATEGORY_TEMPLATE = "GET_CATEGORY_TEMPLATE";
    public static final String GET_CATEGORY_BANNER_FROM_CONTENT_SERVICE = "GET_CATEGORY_BANNER_FROM_CONTENT_SERVICE";
    public static final String GET_CATEGORY_COLLECTIONS_FROM_CONTENT_SERVICE = "GET_CATEGORY_COLLECTIONS_FROM_CONTENT_SERVICE";
    public static final String GET_BREADCRUMB_FROM_NAVIGATION_SERVICE = "GET_BREADCRUMB_FROM_NAVIGATION_SERVICE";
    public static final String GET_LEFT_NAV_FROM_NAVIGATION_SERVICE = "GET_LEFT_NAV_FROM_NAVIGATION_SERVICE";
    public static final String GET_CATEGORY_SILO_MAIN_FROM_CONTENT_SERVICE = "GET_CATEGORY_SILO_MAIN_FROM_CONTENT_SERVICE";
    public static final String GET_CATEGORY_SILO_GRAPHIC_HEADER_FROM_CONTENT_SERVICE = "GET_CATEGORY_SILO_GRAPHIC_HEADER_FROM_CONTENT_SERVICE";
    public static final String GET_DESIGNER_INDEX_FROM_REDIS_CACHE = "GET_DESIGNER_INDEX_FROM_REDIS_CACHE";
    public static final String GET_FAVORITE_DESIGNERS_FROM_PROFILE_SERVICE = "GET_FAVORITE_DESIGNERS_FROM_PROFILE_SERVICE";
    public static final String GET_EMAG_FROM_CONTENT_SERVICE = "GET_EMAG_FROM_CONTENT_SERVICE";

    private LoggingAction() {
    }
}
